on:
  workflow_dispatch: {}
  push:
    branches:
    - docs

jobs:
  copy-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy
      uses: cpina/github-action-push-to-another-repository@v1.6
      env:
        SSH_DEPLOY_KEY: ${{ secrets.OMD_CONSOL_DE_KEY }}
      with:
        source-directory: 'docs/'
        destination-github-username: 'ConSol'
        destination-repository-name: 'omd-consol-de'
        target-directory: 'content/en/docs/plugins/check_vsphere'
        commit-message: |
          update check_vsphere docs

          https://github.com/ConSol/check_vsphere/actions/workflows/deploy-docs.yml
        user-email: 'devnull@consol.de'
        user-name: '/dev/null'
